name: node build lint test

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:

  build_lint_test:

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
      - name: Install fitting npm version
        run: npm i -g npm@8.5.5
      - name: Lint code
        run: npm run lint
      - name: Test code
        run: npm run test
      - name: Build project
        run: npm run build
